vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    mappings:
            articles_image:
                uri_prefix: /images/articles
                upload_destination: '%kernel.project_dir%/public/images/articles'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                
                inject_on_load: false
                delete_on_update: true
                delete_on_remove: true